server:
  port: 8070

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
